// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVF8c7yuZJISJENacMU392lyHpuBlcYmQ',
    appId: '1:1008646625679:web:1b8dad654a7297935853fa',
    messagingSenderId: '1008646625679',
    projectId: 'auth-e4ddd',
    authDomain: 'auth-e4ddd.firebaseapp.com',
    storageBucket: 'auth-e4ddd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4CQNBh0pbuL3FXgWx54Df3EyZgdyOZyY',
    appId: '1:1008646625679:android:e7bf7dfabb03c21b5853fa',
    messagingSenderId: '1008646625679',
    projectId: 'auth-e4ddd',
    storageBucket: 'auth-e4ddd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvLCtL2O1gwXmkbYaD-etC7xEjwVX1NdY',
    appId: '1:1008646625679:ios:a24540662109dc0b5853fa',
    messagingSenderId: '1008646625679',
    projectId: 'auth-e4ddd',
    storageBucket: 'auth-e4ddd.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvLCtL2O1gwXmkbYaD-etC7xEjwVX1NdY',
    appId: '1:1008646625679:ios:0ec8caa3d76310275853fa',
    messagingSenderId: '1008646625679',
    projectId: 'auth-e4ddd',
    storageBucket: 'auth-e4ddd.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
